### ISSUE TITLE
Tray Publisher: Show last available version

### ISSUE THREAD

**Issue by antirotor** [ynput/ayon-traypublisher#1]
## Feature

Old standalone publisher showed last published version on selected context:

![image](https://user-images.githubusercontent.com/33513211/196960296-eadd96cd-bafe-4008-9e23-30bd706efa58.png)

This is feature missing in Tray Publisher

[cuID:[OP-6736](https://app.clickup.com/t/861najw89)]

**Comment by jakubjezek001** [comment]
This had been implemented and is available on demand in `ayon+settings://traypublisher/simple_creators` as **allow_version_control** attribute.
