### ISSUE TITLE
Improve "invalid context" created from EditorialSimple creator when parent context has no task

### ISSUE THREAD

**Issue by robin-ynput** [ynput/ayon-traypublisher#8]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Please describe the feature you have in mind and explain what the current shortcomings are?

I tried to run the `Editorial Simple` creator from a parent context with no task associated.
This properly detect the new Shot as "Products to publish" but those are marked as invalid.

The Tooltip suggest to check the details, but there is really no clue to what's going on and how to fix it.

![image](https://github.com/user-attachments/assets/d499a78b-4bdf-4408-8369-a84bb5ae3325)

### How would you imagine the implementation of the feature?

Maybe the "Create >>" button should be disabled while there is no Task in the context. 

### Are there any labels you wish to add?

- [X] I have added the relevant labels to the enhancement request.

### Version
ayon_traypublisher - 0.2.6-dev.1
ayon_core - 0.4.4

**Comment by robin-ynput** [comment]
I found a work-around working on Resolve :
1. create the instance with `folderPath` being the parent folder
2. adjust `folderPath` to become the hierarchy to create (.e.g. `/shots/seq01/shA`) on collect

**Comment by jakubjezek001** [comment]
@robin-ynput wasn't this solved by https://github.com/ynput/ayon-core/pull/880?

**Comment by johhnry** [comment]
Hi, I have the same issue reported here on Discord: https://discord.com/channels/517362899170230292/563751989075378201/1288424522986557512
@jakubjezek001 can you reproduce the issue?

**Comment by johhnry** [comment]
@robin-ynput I can confirm that it works with the latest commit (f7dea3f6b56258933d0205fad08d0ac0e25360b3), thanks!
